[tool.poetry]
name = "my-neo4j-project"
version = "0.1.0"
description = ""
authors = ["Badry2022 <rasha.mohamed@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
neo4j = "^4.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
